
// This file has been generated by the GUI designer. Do not modify.
namespace Shifted_Games_Launcher_GTK
{
	public partial class About
	{
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.TextView txtabout;
		
		private global::Gtk.Button button_GetLatestRelease;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Shifted_Games_Launcher_GTK.About
			this.Name = "Shifted_Games_Launcher_GTK.About";
			this.Title = global::Mono.Unix.Catalog.GetString ("About the Launcher");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Shifted_Games_Launcher_GTK.About.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.txtabout = new global::Gtk.TextView ();
			this.txtabout.Buffer.Text = "Shifted Games Launcher\n\nVersion: {VER}\nCodename: {CODENAME}\n\nLead Programmer and " +
			"GUI designer: Michael VanOverbeek\n\nWebsite: http://www.shiftgames.ml\n\n";
			this.txtabout.CanFocus = true;
			this.txtabout.Name = "txtabout";
			this.scrolledwindow2.Add (this.txtabout);
			w1.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.scrolledwindow2]));
			w3.Position = 0;
			// Internal child Shifted_Games_Launcher_GTK.About.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "dialog1_ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button_GetLatestRelease = new global::Gtk.Button ();
			this.button_GetLatestRelease.CanFocus = true;
			this.button_GetLatestRelease.Name = "button_GetLatestRelease";
			this.button_GetLatestRelease.UseUnderline = true;
			this.button_GetLatestRelease.Label = global::Mono.Unix.Catalog.GetString ("Check For Updates");
			this.AddActionWidget (this.button_GetLatestRelease, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.button_GetLatestRelease]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.buttonOk]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 601;
			this.DefaultHeight = 424;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.CloseAbout);
		}
	}
}
